#!/bin/bash
# Copyright (C) 2017  Dindin Hernawan <root@dev.xentaos.org>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

figlet svg2png
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls _xenta_os_art*svg)
do
  name=${file%%.svg}
  # Untuk ukuran yang mau di export ke png
  # Silahkan Isi disini :
  height="537"
  width="987"
  echo "Export Berkas $name..."
  inkscape $name.svg --export-png=$name.png --export-height=$height --export-width=$width
  echo "Berhasil.."
done

